### ISSUE TITLE
How to collapse Treeview in Select a Task Sequence by default

### ISSUE THREAD

**Issue by JerichoJones** [FriendsOfMDT/PSD#127]
To make the selection screen more readable I'd like to make Collapse All the default. How can I do that?

Thanks!

**Comment by PowerShellCrack** [comment]
This currently cannot be controlled by the customsettings.ini (but could be a feature request).

There is a section in the [PSDWizardNew.psm1](https://github.com/FriendsOfMDT/PSD/blob/master/Scripts/PSDWizardNew.psm1#L1158) that provides action to the two buttons when the task sequence page is loaded. This is ideal place to add some additional code that will collapse the tree automatically. In between line 1158 and 1159; add:

```powershell
#collapse all items on load
For($i=0; $i -lt $_tsTabTree.Items.Count; $i++)
{
    $_tsTabTree.Items[$i].IsExpanded = $false;
}
```
Since you are editing the module, it will require you to update your deployment share and create a new boot file. 

**WARNING:**  If at any point you update your deployment share with updated PSD code, it will be lost. 

Let me know if this worked for you

**Comment by JerichoJones** [comment]
I'm having firewall issues so I can't auth but I'll test it as soon as this other issue is resolved.

**Comment by JerichoJones** [comment]
It's working. Thanks!
