### ISSUE TITLE
could not establish trust relationship for the ssl/tls secure

### ISSUE THREAD

**Issue by lupinlicious** [FriendsOfMDT/PSD#191]
Dear all,

I'm wondering how to get past the issue below.

"unable to retrieve directory listing of https://mdtlab/psdproduction/control via webdav. Error message exception calling getresponse with 0 arguments. the underlaying connection was closed could not establish trust relationship for the ssl/tls secure"

.\New-PSDServerCert.ps1 -dnsname 10.10.60.2 -friendlyname mdtlab -validityperiod 2
.\New-PSDServerCert.ps1 -dnsname 10.10.60.2 -friendlyname mdtlab -validityperiod 2 -rootcacertfriendlyname PSDRootCA

WARNING: Unable to Enable https listener for IP 0.0.0.0
WARNING: Check if HTTPS with a SSL Certificate exist for the Default Web Site
WARNING: Unable to Add certificate to Default Web Site
WARNING: Check if HTTPS with a SSL Certificate exist for the Default Web Site

netstat -an | findstr :443
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING
  TCP    [::]:443               [::]:0                 LISTENING

Thaaanks!

**Comment by PScherling** [comment]
Hey,
so you have enterde those two commands is that correct?
_.\New-PSDServerCert.ps1 -dnsname 10.10.60.2 -friendlyname mdtlab -validityperiod 2
.\New-PSDServerCert.ps1 -dnsname 10.10.60.2 -friendlyname mdtlab -validityperiod 2 -rootcacertfriendlyname PSDRootCA_

And you are aware of the fact, that you have entered an IPAdress by "-dnsname"? Was that on purpose?
Can you explain your setup a bit more? Because I think there is a problem with Name Resolution and your created Certificate.
I assume that you have a "Standalone" Setup without PKI and AD etc.?

**Comment by lupinlicious** [comment]
Hello,

Yes I ran both commands, I have tried both with ip and hostname.
The lab network I have is quite simple, ony Windows server and a client, no ad or anything else.
