### ISSUE TITLE
Non-localized User and Group Names

### ISSUE THREAD

**Issue by FLeven** [FriendsOfMDT/PSD#50]
It should be mentioned to use an English based 'OsLanguage' OS, because the security groups are not localized in the install script.

For PowerShell Cmdlets the groups can be translated and icacls.exe can work with SID's directly.

Will I run into more problems when continuing with a non English OS, after fixing the group names ?

**Comment by GeoSimos** [comment]
This is a very interesting observation, will discuss it with the team as it is a valid scenario, however we do support for the time being **only** English based WIM files.

**Comment by FLeven** [comment]
I made two changes to the code, in one place you can use a SID instead of the name, in another place this was not possible and I had to replace a name with language "dependent" variable. I will test this soon with the new version. To get started, a comment  would be enough to point users to the line were they will have to do changes. This would save some time and frustration.

**Comment by DeploymentBunny** [comment]
> I made two changes to the code, in one place you can use a SID instead of the name, in another place this was not possible and I had to replace a name with language "dependent" variable. I will test this soon with the new version. To get started, a comment would be enough to point users to the line were they will have to do changes. This would save some time and frustration.

Hi, can you tell us in what script the issue is, not sure if we are talking about the installer or in some other script?

**Comment by FLeven** [comment]
455-461 **install-psd.ps1** for example.

**Comment by DeploymentBunny** [comment]
Thank you!
/m

**Comment by GeoSimos** [comment]
Very nice, the code will be modified to use SIDs instead of their friendly names for the icacls part, however for the Grant-SMBShare it is not possible to use SIDs.
I will do the changes and test, and will try to find a way around for the powershell cmdlets.
Do the Grant-SMBShare and New-SMBShare create a problem also in non English-US setups?

**Comment by FLeven** [comment]
Sure, they do, the account name does not exist on the OS.

**Comment by FLeven** [comment]
You could get the localized account name of **everyone** by running:

`get-acl C:\Users\ | select AccessToString`

and 

`get-acl 'C:\Program Files\' | select AccessToString`

for the **creator owner** ....

**Comment by GeoSimos** [comment]
Hi FLeven,
The get-acl cmdlet returns the access control entries (ACE) in the ACL, it is practical for other actions, however, to have a true multilanguage solution we have to achieve this without over-coding in the solution.
So, after researching a bit the solution would be:

1. Have a list of the well-known SIDs used in Windows and in the solution, we don't need every each one of them.
2. Select a number of languages used and have a mapping between the well-known SIDs and their names or derive the localized name by using the SID only.
3. Use the SID where possible instead of the Username string.

Unfortunately, Grant-SMBShare doesn't support SIDs for the ACEs but expects String names, the same applies to New-SMBShare too.

Please bear with us as we're progressing on this matter, it is a good thing to cover that because we are working on the new installer solution, and it will be good to have this functionality also.

**Comment by baardhermansen** [comment]
> You could get the localized account name of **everyone** by running:
> 
> `get-acl C:\Users\ | select AccessToString`
> 
> and
> 
> `get-acl 'C:\Program Files\' | select AccessToString`
> 
> for the **creator owner** ....

Surely it must be better to use
`Get-LocalUser | Select-Object -ExpandProperty Name` to get the localized names, no?

**Comment by GeoSimos** [comment]
> > You could get the localized account name of **everyone** by running:
> > `get-acl C:\Users\ | select AccessToString`
> > and
> > `get-acl 'C:\Program Files\' | select AccessToString`
> > for the **creator owner** ....
> 
> Surely it must be better to use `Get-LocalUser | Select-Object -ExpandProperty Name` to get the localized names, no?
> 
> Picture showing a test i did on a Spanish base version of Windows 10. ![image](https://user-images.githubusercontent.com/28291585/203148309-2f12ecc2-750e-4caf-b82a-743f5d9768e5.png)

Yes! The Get-LocalUser worked fine for the scenario and is the best candidate to create a dynamic solution, this is what I was checking a couple of days ago.
Thank you @baardhermansen!

**Comment by baardhermansen** [comment]
Regarding line 460 of Install-PSD.ps1, you could also get the localized name of the SMB share (since it's != local user name) by running 
`$localizedSMBName = (Get-SmbShareAccess -Name $psDeploymentShare).AccountName`

I don't have a server to test on for the moment, so i don't see the CREATOR OWNER on the folder rights. I wonder if that right shows up in the above command? If so, then it should be treated as an array. Just a thought.

**Comment by GeoSimos** [comment]
There are also techniques to derive the localized account name by using .Net methods in PowerShell, this is an example https://shellgeek.com/convert-sid-to-username-in-powershell-and-cmd/.

**Comment by baardhermansen** [comment]
> There are also techniques to derive the localized account name by using .Net methods in PowerShell, this is an example https://shellgeek.com/convert-sid-to-username-in-powershell-and-cmd/.

Yeah, just that in your example one have to know the SID beforehand. Not an issue if you do as you mentioned earlier, keep a list of well-known SIDs.

**Comment by GeoSimos** [comment]
For special accounts and groups, you can't use the Get-LocalUser cmdlet, thus you need to find another way to retrieve their details. The list of well-known SIDs exists -and gets updated- since the beginning of Windows NT, so this is not 
 hit in the dark matter. Here is the list if you're interested: https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids.
