### ISSUE TITLE
Error during deployroot network access validation

### ISSUE THREAD

**Issue by yckbrd** [FriendsOfMDT/PSD#63]
<img width="513" alt="Get-PSDContent_return_var_001" src="https://user-images.githubusercontent.com/99958208/190881482-f3280a1d-9d2b-4ec1-a2ef-1e20de1523cd.PNG">
<img width="513" alt="Get-PSDContent_return_var_002" src="https://user-images.githubusercontent.com/99958208/190881483-a54da101-63f4-4dee-be6b-0232ba660c80.PNG">
<img width="513" alt="Get-PSDContent_return_var_003" src="https://user-images.githubusercontent.com/99958208/190881484-516fc52b-a1d4-4ad9-9f21-2cbd67ab322e.PNG">
<img width="513" alt="Get-PSDContent_return_var_004" src="https://user-images.githubusercontent.com/99958208/190881486-3a45383f-6e7e-4ebf-8d11-a84ecb209ded.PNG">

**Comment by BROuardSOLutions** [comment]
The error is not rooted network access denial as it might seem on the first look. The files are copied without problems. The error comes from an erronous variable which is returned after the execution of `Get-PSDContent` which includes the output of `Copy-PSDFolder`. Strangely this only happens when `Get-PSDContent` is called whithin the script. When I tried the command `$control = Get-PSDContent -Content "Control"` manually in a separate window the variable was fine.

Adding `| out-null` to `Get-PSDContentUNC -content $content -destination $dest` in `PSDDeploymentShare.psm1` (Line 212) fixed the issue for me.

**Comment by ASlowTurtle** [comment]
Probably it's the output from xcopy #49 
However a new version was just released. In this version the xcopy output is nulled.

**Comment by GeoSimos** [comment]
> The error is not rooted network access denial as it might seem on the first look. The files are copied without problems. The error comes from an erronous variable which is returned after the execution of `Get-PSDContent` which includes the output of `Copy-PSDFolder`. Strangely this only happens when `Get-PSDContent` is called whithin the script. When I tried the command `$control = Get-PSDContent -Content "Control"` manually in a separate window the variable was fine.
> 
> Adding `| out-null` to `Get-PSDContentUNC -content $content -destination $dest` in `PSDDeploymentShare.psm1` (Line 212) fixed the issue for me.

Can you please provide the Bootstrap.ini settings for the deployment share? My understanding from the shots above is that you're using the UNC path of the Deployment Share but this method is not supported, you have to use the http/https based url of your Deployment Share.
The solution contains all the needed scripts to prepare the infrastructure (IIS, Standalone CA) to support https based installations, you will find them in the Tools folder of PSD.

**Comment by GeoSimos** [comment]
And check the guidance provided here too https://github.com/FriendsOfMDT/PSD/issues/54#issuecomment-1294141151.
