### ISSUE TITLE
Copy-PSDFolder function in PSDUtility.psm1

### ISSUE THREAD

**Issue by zebulun78** [FriendsOfMDT/PSD#68]
When copying the OS image from a UNC path to the cache, if there are any spaces in the OS folder, the xcopy line is not interpreted appropriately as it sees spaces as the next parameter.

### Line 519 should be:
```PowerShell
$null = Start-Process xcopy -ArgumentList """$s"" ""$d"" /s /e /v /d /y /i" -NoNewWindow -Wait -Passthru -RedirectStandardOutput xcopy
```

**Comment by GeoSimos** [comment]
Hello,

Are you trying to deploy via the UNC path of DeployRoot in Bootstrap.ini? Because this won't work, you have to use the http/https method.

**Comment by zebulun78** [comment]
It works fine. I did read those, and am pretty baffled why you're suggesting it won't work when UNC support is clearly built in. If you make that code change I supplied, it works.

**Comment by GeoSimos** [comment]
The whole point is that UNC based deployment is a deprecated method, moreover it is not supported or endorsed from the Development Team, this brings us to the decision that there will be no further code investment on this feature because the supported scenarios have been built around web services and the technologies that complement them (e.g. BITS). 

The code is open, and you are free to manipulate it to your liking and as you see fit, we will check out your suggestion, however for such changes you will have to create a pull request with the proposed change. 
There is no guarantee that it will be incorporated though.
