### ISSUE TITLE
Select Applications Wizard not functioning 

### ISSUE THREAD

**Issue by carlos8177** [FriendsOfMDT/PSD#80]
Hi PSD Team!,

I have a minor issue I have run into hoping for some guidance. I cannot get the application selection to work correctly in the task sequence.

When selecting the applications in the Wizard and starting the task sequence the install Applications script meant to install the applications via the deployment wizard does nothing during the task sequence.

I can create task sequences and add the applications in that way and it works or add them to the custom.ini file.

But I would like the ability to use the Deployment Wizard and select the apps if possible and have the install.

Hope that makes sense 

Regards Carl

**Comment by PowerShellCrack** [comment]
Sorry to hear this is an issue; there is a known bug with applications search or if the applications haven't yet been toggled as enabled/disabled. Also keep in mind bundles do not work yet in this release. We will need more details and logs to see if this issue is related. Please refer to this recent resolved issue: [https://github.com/FriendsOfMDT/PSD/issues/74](https://github.com/FriendsOfMDT/PSD/issues/74)

Let us know if this helped.

**Comment by carlos8177** [comment]
Thanks all I found the issue by putting in the Property SkipApplications=NO in the customini file and app selection appears to be working.

**Comment by GeoSimos** [comment]
Great to hear that it worked for you @carlos8177, this is the reason we usually ask for configuration files and logs, so we  understand what is being set and how the solution is going to behave.
