### ISSUE TITLE
Update Deployment Share Slow

### ISSUE THREAD

**Issue by deronsizemore** [FriendsOfMDT/PSD#82]
I got my PS Deployment share set up and then added the OS, drivers and a few applications. I then try to update the deployment share and it never seems to complete. I started the update a couple days ago around 5pm and then checked it the next morning and it was still updating. Any idea what may cause this? Too many drivers or something possibly? I downloaded the Dell Deploy Driver pack for the model laptop we're imaging, but it does seem like there's quite a few drivers that get's included for some reason. In the past when I've setup MDT I feel like I've had 12-15 drivers total but this driver pack probably has 45 or so.

Any thoughts are appreciated. Thanks!

**Comment by GeoSimos** [comment]
Hi,
Are you referring to the fact of creating the boot image when you update the deployment share?
If yes, then adding all those drivers is generally not a good idea.
Please provide more details for your scenario, so we can assist you further, also take a look in the documentation and especially the drivers part because the PSD solution for the deployment of O/S uses the containerized drivers method instead of the traditional Out-of-Box-Drivers of MDT, here is the link  to the docs https://github.com/FriendsOfMDT/PSD/blob/master/Documentation/PowerShell%20Deployment%20-%20Operations%20Guide.md.

**Comment by deronsizemore** [comment]
Sorry for the confusion. I've read through all the docs and feel like I've got a decent idea of what I'm doing. I actually have a regular deployment share configured and working with Windows 11 without issue currently. So I feel like i'm not completely ignorant with the process. That said, when I've created my PS Deployment Share and configured everything, i.e., added OS drivers, PE drivers, bootstrap.ini, customsettings.ini, WinPE selection profile, etc., and then I click "update deployment share" so that I can then go grab the .wim file inside of WDS, updating the deployment share takes forever and never finishes. It just sits there forever. I've let it sit for nearly an entire day and finally just stop execution. 

I ended up just deleting the newly created PS Deployoment Share and using the regular deployment share and it's working. Unfortunately I don't have anymore time to work the issue I was having at the moment.
