### ISSUE TITLE
Applications not showing up unless adding * filter

### ISSUE THREAD

**Issue by laramy2020** [FriendsOfMDT/PSD#87]
This is the default view i get in the application pane
![image](https://github.com/FriendsOfMDT/PSD/assets/1227781/ef701c27-b035-4897-bb1c-a74766f721c9)
if i add an * to my filter all applications show
![image](https://github.com/FriendsOfMDT/PSD/assets/1227781/0995e1e4-ee27-422d-b041-33fe680ee458)
![image](https://github.com/FriendsOfMDT/PSD/assets/1227781/637ea5db-0453-472c-9adc-6068ee88e76d)

but if i select an application that is not shown by default it will not install. None are bundles. Some are without source files as they are installed through chocolatey
I also enabled skipApplications=no in my customsettings.ini like in #74

**Comment by PowerShellCrack** [comment]
There is a known issue with apps that have not been toggled as enabled. Meaning if you initially add an app, by default it is enabled, however in the xml, there is no attribute that states enabled="true". When the UI loads the apps, the UI is looking for that attribute value. Since its null, it considered NOT TRUE in UI then hides it. The * triggers the UI to only looks for what is does NOT have an attribute of enabled="**false**". 

As a workaround: toggle the app as disabled then toggle it to enabled; thus it will add the needed attribute. Does that show up then?

**Comment by PowerShellCrack** [comment]
For the issue where non shown apps aren't installing: are you saying when you use the * to show the app, then you select them, then you click thru to the summary, you see them in the list, but the task sequence doesn't install them? Can you confirm the task sequence has the application task enabled and selected to install multiple applications?

![image](https://github.com/FriendsOfMDT/PSD/assets/20599825/bfac75b2-3de0-4e26-b88f-daf2f86f1662)

**Comment by laramy2020** [comment]
So I don't know what happened between then and now, but applications started started installing properly before doing the enable toggle, and the enable toggle is now showing all applications.

So things seem to be working now.

**Comment by GeoSimos** [comment]
Hi @laramy2020,
Issue #74 has all the info you need for the time being and until we release a fix for this known issue, please read the whole thread as it will help you understand the issue.
