### ISSUE TITLE
Task Sequence Failed + Propperties deployment share windowspe hangups.

### ISSUE THREAD

**Issue by kl0t3** [FriendsOfMDT/PSD#98]
Hi, 

We manage to get into windowspe and selecting the image.
Once the partitioning steps are done and it wants to start task sequence we get the following error.

Task sequence failed, Return code is -2147467259

What specifically does this mean?
We tried removing as much tasks as possible in the task sequence just installing OS.
Sadly still receiving the same error.
![task sequence](https://github.com/FriendsOfMDT/PSD/assets/148080129/833e17f0-e361-4867-a004-cec726546750)

Also we have constant crashing when trying to accessing Windows PE panel under propperties of deployment share
Is there any way fix to this?
![crashing](https://github.com/FriendsOfMDT/PSD/assets/148080129/392edf84-6f70-4a82-806e-d468bd2a0c44)

**Comment by pimpmyname2** [comment]
Sometimes it happens to me aswell, i went to diskpart, select disk x, clean, create partition primary, reboot that did the trick in my case. If it didnt work, double check your IIS configs

And regarding crash on WinPE panel go to cmd and type "mkdir -p C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\x86\WinPE_OCs". WinPE for windows 11 doesnt include x86 folder

**Comment by 3pichaxz0r** [comment]
-2147467259 is a generic/default error code. Dig into your log files on the device to figure out a more specific reason for the error. smsts.log is the main log file

**Comment by 3pichaxz0r** [comment]
As for the crashing with the deployment workbench when trying to access the winpe tab, its because the windows 11 adk no longer provides x86 winpe images. You should just need to copy the files to the x86 directory on your server to fix it. See the follow:

https://www.deploymentresearch.com/notes-from-the-lab-on-windows-adk-for-windows-11-22h2/
https://learn.microsoft.com/en-us/answers/questions/758014/deployment-workbench-crashes-when-opening-the-win

**Comment by kl0t3** [comment]
Adding the map as pimpmyname2 said was enough for the WinPe tab no longer to crash.

Also formatting the drive worked with diskpart, guess the system still had something on the drive that interfered.

Thanks!
